name: tibok
organizationName: Kristina Quinones

settings:
  SWIFT_VERSION: 5.9
  MACOSX_DEPLOYMENT_TARGET: 14.0
  CODE_SIGN_STYLE: Automatic
  CODE_SIGN_IDENTITY: Apple Development
  DEVELOPMENT_TEAM: F2PFRMGC9V

packages:
  swift-markdown:
    url: https://github.com/apple/swift-markdown.git
    from: 0.3.0
  Highlightr:
    url: https://github.com/raspu/Highlightr.git
    from: 2.1.0

targets:
  tibok:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: tibok
        includes:
          - "**/*.swift"
        excludes:
          - Resources/tibok.entitlements
          - Resources/IconLayers
    resources:
      - path: tibok/Resources/Assets.xcassets
        type: file
      - path: tibok/Resources/AppIcon.icns
        type: file
      - path: tibok/Resources/katex
        type: folder
    infoPlist:
      path: tibok/Resources/Info-AppStore.plist
      useBaseLocalizationAsDefault: true
    entitlements:
      path: tibok/Resources/tibok-dmg.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.tibok.editor
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      EXECUTABLE_NAME: tibok
    dependencies:
      - package: swift-markdown
        product: Markdown
      - package: Highlightr
        product: Highlightr

  tibokTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: tibokTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.tibok.editor.Tests
    dependencies:
      - target: tibok
      - package: swift-markdown
        product: Markdown
      - package: Highlightr
        product: Highlightr

schemes:
  tibok:
    build:
      targets:
        tibok: all
    run:
      config: Debug
      executable: tibok
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - tibokTests
    profile:
      config: Release
      executable: tibok
    analyze:
      config: Debug
    archive:
      config: Release
